// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5gVRkXgyxs1DtoipYprhx6Tp3uzJU10',
    appId: '1:169834832987:web:5cd64dc9916c07c851cb7e',
    messagingSenderId: '169834832987',
    projectId: 'flutter-o-2d456',
    authDomain: 'flutter-o-2d456.firebaseapp.com',
    storageBucket: 'flutter-o-2d456.appspot.com',
    measurementId: 'G-4ES1HS675H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfKN7xZen0i4meRx8JsL7dIUhZjzVqp0',
    appId: '1:169834832987:android:39208e6e82775fb051cb7e',
    messagingSenderId: '169834832987',
    projectId: 'flutter-o-2d456',
    storageBucket: 'flutter-o-2d456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUegHPG08bxdJOIImObOkxYBVAG5bgSrw',
    appId: '1:169834832987:ios:4fec4b5041c8e32751cb7e',
    messagingSenderId: '169834832987',
    projectId: 'flutter-o-2d456',
    storageBucket: 'flutter-o-2d456.appspot.com',
    androidClientId: '169834832987-m9obmkvokc397n8e96dn9up159m01ld0.apps.googleusercontent.com',
    iosClientId: '169834832987-hppmtr1l816t7e0pm4fvhdmfugsnr1j0.apps.googleusercontent.com',
    iosBundleId: 'com.asiya.halalrestaurants',
  );

}